apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          # image: IMAGE_URL/reflection-auth-server:latest #dockerhub ზე განთავსებული იმიჯია საჭირო
          image: IMAGE_URL
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"          # Reduced CPU request
              memory: "128Mi"      # Reduced Memory request
            limits:
              cpu: "100m"          # Adjusted CPU limit
              memory: "128Mi"
          env:
            - name: EUREKA_SERVER_ADDRESS
              value: "http://reflect-service-registry:8761/eureka"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AUTH_SERVER
              value: http://34.121.119.90:8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: auth-server
